name: Archive README with Timestamp

on:
  push:
    paths:
      - README.md
  workflow_dispatch:

jobs:
  archive-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current timestamp
        id: timestamp
        run: echo "ts=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Copy README.md to archive with timestamp
        run: |
          mkdir -p archive
          cp README.md "archive/README-${{ steps.timestamp.outputs.ts }}.md"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add archive/
          git commit -m "Archived README.md as README-${{ steps.timestamp.outputs.ts }}.md"
          git push
        continue-on-error: true
